#!/bin/sh

# xinitrc runs automatically when you run startx.

# There are some small but important commands that need to be run when we start
# the graphical environment. I keep those commands in ~/config/xprofile because
# that file is run automatically if someone uses a display manager (login
# screen) and so they are needed there. To prevent doubling up commands, I
# source them here with the line below.

# export STATUSBAR="i3blocks" # Uncomment this line when using i3.

. ~/.xprofile

# Your default LARBS WM is determined in your `~/.profile` on login.  Here we
# run the proper command to run when the graphical environment starts.

# Comment/uncomment these lines depending on what wm you want to use. Also
# check the i3blocks line above.
numlockx on
#~/.screenlayout/layout.sh
xrandr --output DVI-D-0 --mode 1920x1080 --pos 0x0 --rotate right
xrandr --output HDMI-0 --primary --mode 1920x1080 --pos 1080x524 --rotate normal
wal --theme sexy-derp
ssh-agent dwm
xrandr --output DVI-D-0 --mode 1920x1080 --pos 0x0 --rotate right
xrandr --output HDMI-0 --primary --mode 1920x1080 --pos 1080x524 --rotate normal 
#sleep 500
#~/.screenlayout/layout.sh
# ssh-agent i3
